/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: B1Blender (https://sketchfab.com/B1Blender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-sports-basket-ball-game-asset-pbr-model-c41753d4ea74472a991a93b709889930
Title: 3D Sports Basket Ball Game Asset PBR Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Ball = (props) => {
  const { nodes, materials } = useGLTF('/models/3d_sports_basket_ball_game_asset_pbr_model.glb')
  const ballRef = useRef()

  const {scene} = useGLTF('/models/3d_sports_basket_ball_game_asset_pbr_model.glb')

  useGSAP(() => {
   
    
    if (ballRef.current) {
      gsap.to(ballRef.current.position, {
        y: ballRef.current.position.y - 0.2,
        x: ballRef.current.position.x - 0.4,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []); // Ensure the effect runs only once (on mount)
  
  return (
    <group ref={ballRef}{...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.133}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.basket_ball_Material_0.geometry}
            material={materials.Material}
            position={[0, 107.432, 0]}
          />
        </group>
      </group>
    </group>
  )
}

export default Ball ;
useGLTF.preload('/models/3d_sports_basket_ball_game_asset_pbr_model.glb')
