/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Christos77 (https://sketchfab.com/Christos77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-weights-01d5fbe1cfb748569ae3c2ebf1f1abe8
Title: hand weights
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Dumbbells = (props) => {
  const dumbbellRef = useRef()

  const { nodes, materials } = useGLTF('/models/hand_weights.glb')
  
  const {scene} = useGLTF('/models/hand_weights.glb')

  useGSAP(() => {

    if (dumbbellRef.current && dumbbellRef.current.current) {
      gsap.to(dumbbellRef.current.current.position, {
        x: dumbbellRef.current.current.position.x + 0.4,
        y: dumbbellRef.current.current.position.y + 0.2,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
    
  }, []); // Ensure the effect runs only once (on mount)
  
  return (
    <group ref={dumbbellRef}{...props} dispose={null} >
      <mesh 
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
      />
    </group>
  )
}

export default Dumbbells;
useGLTF.preload('/models/hand_weights.glb')
