/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anim3dmodel (https://sketchfab.com/anim3dmodel)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/headphone-af9811ea9a6247efb1c4a1587c4a67f2
Title: HEADPHONE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Headphone = (props) =>{
  const headphoneRef = useRef()

  const { nodes, materials } = useGLTF('/models/headphone.glb')
  const {scene} = useGLTF('/models/headphone.glb')

  useGSAP(() => {
    console.log(headphoneRef);
    console.log(headphoneRef.current);

    if (headphoneRef.current) {
      gsap.to(headphoneRef.current.position, {
        x: headphoneRef.current.position.x + 0.4,
        y: headphoneRef.current.position.y + 0.2,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []); // Ensure the effect runs only once (on mount)
  
  return (
    <group ref={headphoneRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle_headset_cover_0.geometry}
          material={materials.headset_cover}
          position={[133.774, 0, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={91.571}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle001_HSC4_0.geometry}
          material={materials.HSC4}
          position={[196.283, 0, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={95.881}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle002_HSC5_0.geometry}
          material={materials.HSC5}
          position={[239.392, 0, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={42.311}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={materials.Sphere__0}
          position={[140.926, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[25.965, 72.098, 72.098]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HEADSET_HEADSET_0.geometry}
          material={materials.HEADSET}
          position={[-0.008, 216.259, 0.16]}
          rotation={[0, -0.018, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_HSC2_0.geometry}
          material={materials.HSC2}
          rotation={[0, -0.018, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002_HSC3_0.geometry}
          material={materials.HSC3}
          position={[-8.919, 285.389, 0.002]}
          rotation={[0, -0.018, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

export default Headphone ;
useGLTF.preload('/models/headphone.glb')
