/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-circle-540ff21ac0f54a038df6f634c7cce726
Title: React logo circle
*/

import React, { useRef } from 'react'
import { Float , useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'


const ReactLogo =(props) => {

  const reactRef = useRef()
  const { nodes, materials } = useGLTF('/models/react_logo_circle.glb')
  const {scene} = useGLTF('/models/react_logo_circle.glb')
  
  useGSAP(() => {

    if (reactRef.current) {
      gsap.to(reactRef.current.position, {
        x: reactRef.current.position.x + 0.4,
        y: reactRef.current.position.y + 0.2,
        duration: 1.5,
        repeat: -1,
        yoyo: true
      });
    }
  }, []); 
  return (
    <Float ref={reactRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['React-Logo_Material002_0'].geometry}
            material={materials['Material.002']}
            position={[0, 7.935, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[39.166, 39.166, 52.734]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Backdrop_Material001_0.geometry}
            material={materials['Material.001']}
            position={[-17.091, 7.935, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[247.854, 247.854, 52.734]}
          />
        </group>
      </group>
    </Float>
  )
}

export default ReactLogo ;
useGLTF.preload('/models/react_logo_circle.glb')
